package com.db.awmd.challenge.client;

public interface AccountTransactionErrorCodes {
	int EMPTY_TRANSACTION_REQUEST = 1000;
	int INVALID_SOURCE_ACCOUNTID = 1001;
	int INVALID_TARGET_ACCOUNTID = 1002;
	int INVALID_FUND_TRANSFER_AMOUNT = 1003;
	int INVALID_TRANSACTION_ID = 1004;
	int INSUFFICIENT_FUNDS_IN_SOURCE_ACCOUNT = 1005;
	int SOURCE_ACCOUNT_SAME_AS_TARGET_ACCOUNT = 1006;
	int NULL_EMPTY_TRANSACTION_ID = 1007;
}